#Deep Learning - Based Weed and Crop Detection in Agricultural Fields (Major)



# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHk6OOPlwxkIVqm07qRWJybzapo7TECe
"""

!pip install ultralytics
!pip install wandb

from google.colab import files
uploaded = files.upload()

import zipfile

with zipfile.ZipFile("archive (3).zip",'r') as zip_ref:
    zip_ref.extractall("/content")

print("Extraction Completed")

import os
os.listdir("/content")

import os
os.listdir("/content/WeedCrop.v1i.yolov5pytorch")

import yaml

data = {
    'train': '/content/dataset/images/train',
    'val': '/content/dataset/images/val',
    'test': '/content/dataset/images/test',
    'nc': 2,
    'names': ['Crop','Weed']
}

with open('/content/data.yaml', 'w') as f:
    yaml.dump(data, f)

print("data.yaml created successfully")

!ls /content

!ls /content/WeedCrop.v1i.yolov5pytorch

!ls /content/WeedCrop.v1i.yolov5pytorch/train

!ls /content/WeedCrop.v1i.yolov5pytorch/valid

!cat /content/WeedCrop.v1i.yolov5pytorch/data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/WeedCrop.v1i.yolov5pytorch/data.yaml
# 
# train: /content/WeedCrop.v1i.yolov5pytorch/train/images
# val: /content/WeedCrop.v1i.yolov5pytorch/valid/images
# test: /content/WeedCrop.v1i.yolov5pytorch/test/images
# 
# nc: 2
# names: ['crop', 'weed']

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/WeedCrop.v1i.yolov5pytorch/data.yaml",
    epochs=50,
    imgsz=640
)

from ultralytics import YOLO
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import os

model = YOLO("/content/runs/detect/train/weights/best.pt")

test_images = "/content/dataset/images/test"
test_labels = "/content/dataset/labels/test"

y_true = []
y_pred = []

for img in os.listdir(test_images):

    if not img.endswith((".jpg",".jpeg",".png")):
        continue

    img_path = os.path.join(test_images, img)

    label_path = os.path.join(test_labels, img.rsplit(".",1)[0] + ".txt")

    # prediction
    results = model.predict(img_path, conf=0.25, verbose=False)

    pred_classes = []

    for r in results:
        if r.boxes is not None:
            pred_classes = r.boxes.cls.cpu().numpy().astype(int).tolist()

    # ground truth
    true_classes = []

    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f.readlines():
                true_classes.append(int(line.split()[0]))

    # match lengths
    min_len = min(len(true_classes), len(pred_classes))

    y_true.extend(true_classes[:min_len])
    y_pred.extend(pred_classes[:min_len])

print("Total ground truth:", len(y_true))
print("Total predictions:", len(y_pred))

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Crop","Weed"],
            yticklabels=["Crop","Weed"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

print("Images:", len(os.listdir("/content/dataset/images/test")))
print("Labels:", len(os.listdir("/content/dataset/labels/test")))

!pip install torch torchvision pycocotools opencv-python

import os
import cv2
import matplotlib.pyplot as plt
from torchvision.transforms import functional as F
import torch

model.eval()

test_folder = "/content/dataset/images/test"

image_name = os.listdir(test_folder)[0]
img_path = os.path.join(test_folder, image_name)

print("Using image:", img_path)

img = cv2.imread(img_path)

if img is None:
    print("Image not found. Check path.")
else:
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    img_tensor = F.to_tensor(img_rgb).to(device)

    with torch.no_grad():
        prediction = model([img_tensor])

    boxes = prediction[0]['boxes'].cpu().numpy()

    for box in boxes:
        x1, y1, x2, y2 = map(int, box)
        cv2.rectangle(img_rgb, (x1,y1), (x2,y2), (255,0,0), 2)

    plt.imshow(img_rgb)
    plt.axis("off")
    plt.show()

yolo_to_coco(
    "/content/dataset/images/train",
    "/content/dataset/labels/train",
    "/content/train.json"
)

yolo_to_coco(
    "/content/dataset/images/val",
    "/content/dataset/labels/val",
    "/content/val.json"
)

import torch
import torchvision
from torchvision.datasets import CocoDetection
from torchvision.transforms import functional as F

class CustomCocoDataset(CocoDetection):

    def __getitem__(self, idx):
        img, target = super().__getitem__(idx)

        boxes = []
        labels = []

        for obj in target:
            x, y, w, h = obj["bbox"]
            boxes.append([x, y, x+w, y+h])
            labels.append(obj["category_id"])

        boxes = torch.as_tensor(boxes, dtype=torch.float32)
        labels = torch.as_tensor(labels, dtype=torch.int64)

        target = {
            "boxes": boxes,
            "labels": labels
        }

        img = F.to_tensor(img)

        return img, target

train_dataset = CustomCocoDataset(
    root="/content/dataset/images/train",
    annFile="/content/train.json"
)

val_dataset = CustomCocoDataset(
    root="/content/dataset/images/val",
    annFile="/content/val.json"
)

train_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=4, shuffle=True, collate_fn=lambda x: tuple(zip(*x))
)

val_loader = torch.utils.data.DataLoader(
    val_dataset, batch_size=4, shuffle=False, collate_fn=lambda x: tuple(zip(*x))
)

import torchvision
from torchvision.models.detection import fasterrcnn_resnet50_fpn

model = fasterrcnn_resnet50_fpn(pretrained=True)

num_classes = 3  # background + crop + weed

in_features = model.roi_heads.box_predictor.cls_score.in_features

model.roi_heads.box_predictor = torchvision.models.detection.faster_rcnn.FastRCNNPredictor(
    in_features, num_classes
)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

import os
from torchvision.transforms import functional as F
import cv2
import torch

model.eval()

test_images = "/content/dataset/images/test"
test_labels = "/content/dataset/labels/test"

for img_name in os.listdir(test_images):

    if not img_name.endswith((".jpg",".jpeg",".png")):
        continue

    img_path = os.path.join(test_images, img_name)
    label_path = os.path.join(test_labels, img_name.rsplit(".",1)[0] + ".txt")

    # Read image
    img = cv2.imread(img_path)

    if img is None:
        continue

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_tensor = F.to_tensor(img_rgb).to(device)

    # Prediction
    with torch.no_grad():
        outputs = model([img_tensor])

    pred_labels = outputs[0]['labels'].cpu().numpy()
    scores = outputs[0]['scores'].cpu().numpy()

    # Filter predictions (confidence)
    pred_filtered = [label for label, score in zip(pred_labels, scores) if score > 0.5]

    # Ground truth (YOLO labels)
    true_labels = []
    if os.path.exists(label_path):
        with open(label_path) as f:
            for line in f.readlines():
                cls = int(line.split()[0]) + 1  # +1 for COCO format
                true_labels.append(cls)

    # Match lengths
    min_len = min(len(true_labels), len(pred_filtered))

    y_true.extend(true_labels[:min_len])
    y_pred.extend(pred_filtered[:min_len])

print("Total Samples:", len(y_true))

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5,4))

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Background","Crop","Weed"],
            yticklabels=["Background","Crop","Weed"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Faster R-CNN")

plt.show()

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred, target_names=["Crop","Weed"]))
