#Deep Learning-Based  Weed vs Crop Classification System (Mini 2)



# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tEmzRdbo1pTrpp4PvDbJQa1IwaGFHaEL
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
from google.colab import files
import zipfile
import os
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# ----------------------------
# 1️⃣ Upload Dataset ZIP
# ----------------------------
print("Upload your dataset ZIP file (with agriculture/train and agriculture/test folders inside)...")
uploaded = files.upload()

# Unzip uploaded file
for fn in uploaded.keys():
    with zipfile.ZipFile(fn, 'r') as zip_ref:
        zip_ref.extractall("dataset")

print("✅ Dataset extracted!")

# # ----------------------------
# # 2️⃣ Set Dataset Paths
# # ----------------------------
# train_dir = "dataset/agriculture/Train"   # your dataset has capital T
# test_dir  = "dataset/agriculture/Test"    # capital T

# if not os.path.exists(train_dir) or not os.path.exists(test_dir):
#     raise FileNotFoundError("❌ Could not find Train/Test folders. Please check dataset structure.")

# print("✅ Train folder:", train_dir)
# print("✅ Test folder :", test_dir)

# # ----------------------------
# # 3️⃣ Data Transforms
# # ----------------------------
# IMG_SIZE = 224
# BATCH_SIZE = 16

# train_transforms = transforms.Compose([
#     transforms.Resize((IMG_SIZE, IMG_SIZE)),
#     transforms.RandomHorizontalFlip(),
#     transforms.RandomRotation(15),
#     transforms.ToTensor(),
#     transforms.Normalize([0.485, 0.456, 0.406],
#                          [0.229, 0.224, 0.225])
# ])

# test_transforms = transforms.Compose([
#     transforms.Resize((IMG_SIZE, IMG_SIZE)),
#     transforms.ToTensor(),
#     transforms.Normalize([0.485, 0.456, 0.406],
#                          [0.229, 0.224, 0.225])
# ])

# # ----------------------------
# # 4️⃣ Load Dataset
# # ----------------------------
# full_train_dataset = datasets.ImageFolder(train_dir, transform=train_transforms)
# test_dataset = datasets.ImageFolder(test_dir, transform=test_transforms)

# # Split training into train/val
# val_size = int(0.2 * len(full_train_dataset))
# train_size = len(full_train_dataset) - val_size
# train_dataset, val_dataset = random_split(full_train_dataset, [train_size, val_size])

# train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
# val_loader   = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
# test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

# print(f"🟢 Training samples: {len(train_dataset)}")
# print(f"🟡 Validation samples: {len(val_dataset)}")
# print(f"🔵 Testing samples: {len(test_dataset)}")

# # ----------------------------
# # 5️⃣ Load ResNet50 Model
# # ----------------------------
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# print("Using device:", device)

# model = models.resnet50(pretrained=True)
# num_ftrs = model.fc.in_features
# model.fc = nn.Linear(num_ftrs, 2)  # 2 classes: plants vs weeds
# model = model.to(device)

# criterion = nn.CrossEntropyLoss()
# optimizer = optim.Adam(model.parameters(), lr=1e-4)

# # ----------------------------
# # 6️⃣ Training Loop
# # ----------------------------
# EPOCHS = 10
# best_val_acc = 0

# for epoch in range(EPOCHS):
#     # Train
#     model.train()
#     running_loss, correct, total = 0, 0, 0
#     for imgs, labels in train_loader:
#         imgs, labels = imgs.to(device), labels.to(device)
#         optimizer.zero_grad()
#         outputs = model(imgs)
#         loss = criterion(outputs, labels)
#         loss.backward()
#         optimizer.step()

#         running_loss += loss.item()
#         _, predicted = torch.max(outputs, 1)
#         correct += (predicted == labels).sum().item()
#         total += labels.size(0)

#     train_acc = 100 * correct / total
#     train_loss = running_loss / len(train_loader)

#     # Validation
#     model.eval()
#     val_correct, val_total = 0, 0
#     with torch.no_grad():
#         for imgs, labels in val_loader:
#             imgs, labels = imgs.to(device), labels.to(device)
#             outputs = model(imgs)
#             _, predicted = torch.max(outputs, 1)
#             val_correct += (predicted == labels).sum().item()
#             val_total += labels.size(0)

#     val_acc = 100 * val_correct / val_total

#     print(f"Epoch [{epoch+1}/{EPOCHS}] "
#           f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}% | Val Acc: {val_acc:.2f}%")

#     # Save best model
#     if val_acc > best_val_acc:
#         best_val_acc = val_acc
#         torch.save(model.state_dict(), "best_resnet50.pth")

# # ----------------------------
# # 7️⃣ Testing
# # ----------------------------
# model.load_state_dict(torch.load("best_resnet50.pth"))
# model.eval()

# test_correct, test_total = 0, 0
# with torch.no_grad():
#     for imgs, labels in test_loader:
#         imgs, labels = imgs.to(device), labels.to(device)
#         outputs = model(imgs)
#         _, predicted = torch.max(outputs, 1)
#         test_correct += (predicted == labels).sum().item()
#         test_total += labels.size(0)

# test_acc = 100 * test_correct / test_total
# print(f"🎯 Final Test Accuracy: {test_acc:.2f}%")




# ----------------------------
# 2️⃣ Define Dataset Paths
# ----------------------------
train_dir = "dataset/agriculture/Train"   # capital T
test_dir  = "dataset/agriculture/Test"    # capital T

if not os.path.exists(train_dir) or not os.path.exists(test_dir):
    raise FileNotFoundError("❌ Could not find Train/Test folders. Please check dataset structure.")

print("✅ Train folder:", train_dir)
print("✅ Test folder :", test_dir)

# ----------------------------
# 3️⃣ Image Preprocessing
# ----------------------------
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False   # keep order for confusion matrix
)

# ----------------------------
# 4️⃣ Build Model (CNN)
# ----------------------------
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

# ----------------------------
# 5️⃣ Compile & Train
# ----------------------------
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

history = model.fit(
    train_gen,
    validation_data=test_gen,
    epochs=10
)

# ----------------------------
# 6️⃣ Accuracy & Loss Curves
# ----------------------------
plt.figure(figsize=(12,5))

# Accuracy plot
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training vs Test Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Test Loss')
plt.title('Training vs Test Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

# ----------------------------
# 7️⃣ Confusion Matrix
# ----------------------------
y_true = test_gen.classes
y_pred_probs = model.predict(test_gen)
y_pred = (y_pred_probs > 0.5).astype("int32").flatten()

cm = confusion_matrix(y_true, y_pred)
labels = list(test_gen.class_indices.keys())

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, target_names=labels))



# ✅ Install required libraries
!pip install tensorflow matplotlib seaborn scikit-learn --quiet

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# ----------------------------
# 2️⃣ Define Dataset Paths
# ----------------------------
train_dir = "dataset/agriculture/Train"   # capital T
test_dir  = "dataset/agriculture/Test"    # capital T

if not os.path.exists(train_dir) or not os.path.exists(test_dir):
    raise FileNotFoundError("❌ Could not find Train/Test folders. Please check dataset structure.")

print("✅ Train folder:", train_dir)
print("✅ Test folder :", test_dir)

# ----------------------------
# 3️⃣ Image Preprocessing
# ----------------------------
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False   # keep order for confusion matrix
)

# ----------------------------
# 4️⃣ Build Model (CNN)
# ----------------------------
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

# ----------------------------
# 5️⃣ Compile & Train
# ----------------------------
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

history = model.fit(
    train_gen,
    validation_data=test_gen,
    epochs=15  # more epochs for smoother curve
)

# ----------------------------
# 6️⃣ Accuracy & Loss Curves
# ----------------------------
plt.figure(figsize=(12,5))

# Accuracy plot
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training vs Test Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Test Loss')
plt.title('Training vs Test Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

# ----------------------------
# 7️⃣ Confusion Matrix
# ----------------------------
y_true = test_gen.classes
y_pred_probs = model.predict(test_gen)
y_pred = (y_pred_probs > 0.5).astype("int32").flatten()

cm = confusion_matrix(y_true, y_pred)
labels = list(test_gen.class_indices.keys())

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ----------------------------
# 8️⃣ Classification Report
# ----------------------------
print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, target_names=labels))

# ✅ Imports
import os
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# ----------------------------
# 1️⃣ Define Dataset Paths
# ----------------------------
train_dir = "dataset/agriculture/Train"   # must contain subfolders "plants" and "weeds"
test_dir  = "dataset/agriculture/Test"

if not os.path.exists(train_dir) or not os.path.exists(test_dir):
    raise FileNotFoundError("❌ Could not find Train/Test folders. Please check dataset structure.")

print("✅ Train folder:", train_dir)
print("✅ Test folder :", test_dir)

# ----------------------------
# 2️⃣ Image Preprocessing
# ----------------------------
IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode="nearest"
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)

# ----------------------------
# 3️⃣ Build CNN Model
# ----------------------------
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')   # binary classification
])

# ----------------------------
# 4️⃣ Compile Model
# ----------------------------
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

# ----------------------------
# 5️⃣ Train Model
# ----------------------------
history = model.fit(
    train_gen,
    validation_data=test_gen,
    epochs=20,   # can increase for better results
    verbose=1
)

# ----------------------------
# 6️⃣ Accuracy & Loss Curves
# ----------------------------
plt.figure(figsize=(12,5))

# Accuracy plot
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Test Accuracy')
plt.title('Training vs Test Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Test Loss')
plt.title('Training vs Test Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

# ----------------------------
# 7️⃣ Confusion Matrix
# ----------------------------
y_true = test_gen.classes
y_pred_probs = model.predict(test_gen)
y_pred = (y_pred_probs > 0.5).astype("int32").flatten()

cm = confusion_matrix(y_true, y_pred)
labels = list(test_gen.class_indices.keys())

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ----------------------------
# 8️⃣ Classification Report
# ----------------------------
print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, target_names=labels))

